# -*- coding: utf-8 -*-
"""RA2211003010979_KOTIPALLI_SRIKESH_PBLIComponent_PracticeExperiments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pzaEv-66-EXhb2yhP4pcdgf03MtBGAV
"""

!pip install pandas numpy matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/Olympic_Medal_Tally_History.csv')

df.head()

df.tail()

df.columns

df.info()

df.describe()

df.isnull().sum()

sns.pairplot(df)
plt.show()

sns.distplot(df['year'])

sns.distplot(df['gold'])

sns.histplot(df, x="gold", kde=True)
plt.show()

sns.histplot(df, x="silver", kde=True)
plt.show()

sns.regplot(x='year',y='gold',data=df,line_kws={"color": "red"})
plt.show()

sns.lineplot(x='year',y='gold',data=df)
plt.show()